version: "3.8"
services:
  orchestrator:
    build: ./orchestrator
    ports:
      - "8000:8000"
    volumes:
      - ./orchestrator:/app
    command: uvicorn orchestrator.main:app --host 0.0.0.0 --port 8000 --reload
